@startuml

class Solution43
{
    +main(String[])
    'calls promptForInfo()
    'calls makeFiles()
}

class FileMake
{
    -site
    -author
    -java
    -css

    +promptForInfo()
    'prompts for site, author, java, and css
    'sets the value for the class variables

    -getSite(): String
    'returns site string
    -getAuthor(): String
    'returns author string
    -getJava(): Boolean
    'returns true or false depending on y or n
    -getCss(): Boolean
    'returns true or false depending on y or n

    +makeFiles()
    'makes folders using the information given from user
    'makes file using the information given from user
}

FileMake -- Solution43

@enduml