@startuml

class FileRead
{
    +takeInfoFromFile(): List<String>
    +separateInfo(List<String> info): List<Map<String, String>>
    +printInfoToFile(List<Map<String, String>> separated)
}

class Solution42
{
    +main(String[])
}

Solution42 -- FileRead

@enduml